name: Jake Bronstein
favicon: null
layout_spectrum: 0.3386775271501392
typography_spectrum: 0.7160016337875277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3460633363574743
  lightness: 0.6457933555357158
  saturation: 0.4795702954288572
  rhythmicContrast: 0.33492008107714355
purpose: []
